---
- hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - wait_for_connection: {timeout: 300}
    - setup:

  vars:
    logrotate_package: logrotate
    logrotate_options:
      - weekly
      - rotate 4
      - create
      - dateext
      - su root syslog
    logrotate_global_config: true
    docker_daemon_options:
      log-opts:
        max-size: "100m"

  tasks:
    - name: package install task
      ansible.builtin.import_tasks:
        file: tasks/package_install.yaml
    - name: Install and Configure Logrotate
      import_role:
        name: arillso.logrotate
    - name: Install and Configure Docker
      import_role:
        name: geerlingguy.docker
    - name: Docker dependencies
      import_tasks:
        file: tasks/services/docker-dependencies.yaml
    - name: Portainer deployment
      import_tasks:
        file: tasks/services/portainer/portainer.yaml
